### PR TITLE
relaton/relaton#110 move to shared workflow

### PR DESCRIPTION
**Pull request by CAMOBAP**
- relaton/relaton#110

### CODE REVIEW

**Review by andrew2net — APPROVED** [review]
@CAMOBAP it seems Jekyll's files are moved somewhere, right? Where will they live now? We need to be able to update them.
FYI There are settings in the _config.yml that are repository-specific. It's highly likely they will be subject to change to adapt to other data repositories.

**Comment by CAMOBAP** [comment]
> @CAMOBAP it seems Jekyll's files are moved somewhere, right? Where will they live now? We need to be able to update them. 

Yep, they are in https://github.com/relaton/jekyll-theme-relaton-data-index so we do `checkout` to `src` directory  https://github.com/relaton/support/blob/master/.github/workflows/data-deploy.yml#L24-L27

> FYI There are settings in the _config.yml that are repository-specific. It's highly likely they will be subject to change to adapt to other data repositories.

We have a "base" config file which keeps all common properties: https://github.com/relaton/jekyll-theme-relaton-data-index/blob/main/_config.yml

Also, each `relaton-data-*` repository will have their own `_config.yml` file with repository-specific properties https://github.com/relaton/relaton-data-oasis/pull/6/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883

The workflow merge those yaml files during `deploy` workflow https://github.com/relaton/support/blob/master/.github/workflows/data-deploy.yml#L29-L41 and print result `_config.yml` for troubleshooting

Also I moved jekyll specific gems to reparate `Gemfile.deploy` which is included by `Gemfile` to be able maintain it via `cimas`

---

Also, one notable change is that we don't commit `src/_data` file we copy them from the root of the repository: 

https://github.com/relaton/support/blob/57fa5a5209ecd1cc7f73de5c4b420243bd5bc7db/.github/workflows/data-deploy.yml#L43-L50

For now we only copy `index.yaml`, @andrew2net will it be enought for all repos?

**Comment by andrew2net** [comment]
> Also, one notable change is that we don't commit `src/_data` file we copy them from the root of the repository:

@CAMOBAP If we copy the files from a repo's `data` dir then the Jekyll plugin won't find files in the `src/_data`. The plugin uses files' paths from index https://github.com/relaton/relaton-data-oasis/blob/c9f43701b6f793b097e6c29c49da4dea1a030834/index-v1.yaml#L3

If we need to copy the files we should copy them to root.

> For now we only copy `index.yaml`, @andrew2net will it be enought for all repos?

Where do we copy `index.yaml` to? The indexes are used to find the documents' files in the `data` dir. The plugin fetched the needed metadata from the files. https://github.com/relaton/relaton-data-oasis/blob/c9f43701b6f793b097e6c29c49da4dea1a030834/src/_plugins/jekyll-index.rb#L19
FYI we have versioned index file names. Some of the repos have more than one index file (for compatibility with previous gem versions). So we have the `source` configuration to define an index file name for each data repo. https://github.com/relaton/relaton-data-oasis/blob/c9f43701b6f793b097e6c29c49da4dea1a030834/_config.yml#L57

**Comment by CAMOBAP** [comment]
> If we need to copy the files we should copy them to root.

I can confirm that `data-deploy` workflow copy `inded.yaml` from the root of the repository

> Where do we copy index.yaml to?

`cp index.yaml src/_data`

@andrew2net  is it safe to assume that we only should copy index.yaml from `_config`'s `source` to `src/_data`?

**Comment by andrew2net** [comment]
> @andrew2net is it safe to assume that we only should copy index.yaml from `_config`'s `source` to `src/_data`?

@CAMOBAP we need to copy `data` dir as well. Is `src/_data` a dir where Jekyll runs? If the `src/_data` is a root dir for Jekyll then we need to put an index file and `data` dir there.

**Comment by CAMOBAP** [comment]
Sorry looks like i created data-deploy workflow from outdated code. From what I see rightnow in https://github.com/relaton/relaton-data-oasis/blob/main/src/_plugins/jekyll-index.rb and https://github.com/relaton/relaton-data-oasis/blob/main/.github/workflows/deploy.yml

There is no need to copy index.yaml or data into `src/_data`. `jekyll-index.rb` will take everything from the root of repository

**Comment by CAMOBAP** [comment]
@ronaldtse may I ask you to review it again

Key implementation notes:
- src moved to https://github.com/relaton/jekyll-theme-relaton-data-index
- common properties for `_config.yml` are in https://github.com/relaton/jekyll-theme-relaton-data-index/blob/main/_config.yml and we merge repoistory's `_config.yml` with "common" one
- we don't copy any `index.yaml` or `data` files into `src`
- deploy happens only for `default` branch (main or master)

**Review by ronaldtse — APPROVED** [review]

**Comment by CAMOBAP** [comment]
Hmm, something isn't right generated `index.html` is empty... investigating

**Comment by CAMOBAP** [comment]
> Hmm, something isn't right generated `index.html` is empty... investigating

Fixed, some unwanted files was commited to jekyll template

**Pull request merged**
